{
  "swagger" : "2.0",
  "info" : {
    "description" : "Servicio web de marketing cloud para exponer campañas activas por sucursal, clientes que pertenecen a una campaña activa, campañas activas que pertecenen a un cliente, seguimientos de uun cliente y campaña especifica, insercion de los seguimeitos de un cliente y campaña especifica, detalles de un cliente, y mejor producto a ofertar al cliente",
    "version" : "1.0.0",
    "title" : "Marketing Cloud Services Portafolio",
    "contact" : {
      "email" : "aramosa@elektra.com.mx"
    }
  },
  "host" : "localhost",
  "basePath" : "/prd/marketing/",
  "tags" : [ {
    "name" : "marketing",
    "description" : "Campañas activas",
    "externalDocs" : {
      "description" : "Find out more",
      "url" : "http://swagger.io"
    }
  } ],
  "schemes" : [ "http" ],
  "paths" : {
    "/portfolio/campaigns/{branch}" : {
      "get" : {
        "tags" : [ "marketing" ],
        "summary" : "Campañas activas por numero de sucursal",
        "description" : "Response con id de campaña y descripcion de campaña",
        "operationId" : "getCampaignsByNumber",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "branch",
          "in" : "path",
          "description" : "Numero de sucursal",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "operacion exitosa",
            "headers" : {
              "transactionId" : {
                "type" : "string",
                "description" : "identificador de la transacción en capa de servicios"
              }
            },
            "schema" : {
              "$ref" : "#/definitions/responseCampaigns"
            }
          },
          "404" : {
            "description" : "Error general",
            "headers" : {
              "transactionId" : {
                "type" : "string",
                "description" : "identificador de la transacción en capa de servicios"
              }
            },
            "schema" : {
              "$ref" : "#/definitions/Error"
            }
          }
        }
      }
    },
    "/portfolio/campaignidbranch/clients" : {
      "post" : {
        "tags" : [ "marketing" ],
        "summary" : "Lista de clientes que pertenecen a una campaña por sucursal",
        "description" : "Response con id de campaña y sucursal, descripcion de campaña e informacion de cliente unico",
        "operationId" : "getClientsByCampaign",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "campaingBranch",
          "description" : "Objeto envolvente de la peticion",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/CampaingBranch"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "operacion exitosa",
            "headers" : {
              "transactionId" : {
                "type" : "string",
                "description" : "identificador de la transacción en capa de servicios"
              }
            },
            "schema" : {
              "$ref" : "#/definitions/responseClients"
            }
          },
          "404" : {
            "description" : "Error general",
            "headers" : {
              "transactionId" : {
                "type" : "string",
                "description" : "identificador de la transacción en capa de servicios"
              }
            },
            "schema" : {
              "$ref" : "#/definitions/Error"
            }
          }
        }
      }
    },
    "/portfolio/client/campaigns" : {
      "post" : {
        "tags" : [ "marketing" ],
        "summary" : "Lista de campañas por cliente",
        "description" : "Response de campañas activas al cliente",
        "operationId" : "getCampaignsByClient",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "uniqueClient",
          "description" : "Objeto envolvente de la peticion",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/UniqueClients"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "operacion exitosa",
            "headers" : {
              "transactionId" : {
                "type" : "string",
                "description" : "identificador de la transacción en capa de servicios"
              }
            },
            "schema" : {
              "$ref" : "#/definitions/responseClientesCampaings"
            }
          },
          "404" : {
            "description" : "Error general",
            "headers" : {
              "transactionId" : {
                "type" : "string",
                "description" : "identificador de la transacción en capa de servicios"
              }
            },
            "schema" : {
              "$ref" : "#/definitions/Error"
            }
          }
        }
      }
    },
    "/portfolio/client/detailscamping" : {
      "post" : {
        "tags" : [ "marketing" ],
        "summary" : "Detalle de Campana",
        "description" : "Responde  la Fecha de expiracion (yyyy-MM-dd)",
        "operationId" : "getDetailsCamping",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "uniqueClient",
          "description" : "Objeto envolvente de la peticion",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/UniqueClientIdCamping"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "operacion exitosa",
            "headers" : {
              "transactionId" : {
                "type" : "string",
                "description" : "identificador de la transacción en capa de servicios"
              }
            },
            "schema" : {
              "$ref" : "#/definitions/responseDetailsCamping"
            }
          },
          "404" : {
            "description" : "Error general",
            "headers" : {
              "transactionId" : {
                "type" : "string",
                "description" : "identificador de la transacción en capa de servicios"
              }
            },
            "schema" : {
              "$ref" : "#/definitions/Error"
            }
          }
        }
      }
    },
    "/portfolio/client/tracingclient" : {
      "post" : {
        "tags" : [ "marketing" ],
        "summary" : "Regresa la lista de seguimientos  de un cliente para una campaña especifica",
        "description" : "Response los seguimentos de un cliente y campaña en especifico por parte de portafolio",
        "operationId" : "getTracingClient",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "ClientIdCamping",
          "description" : "Objeto envolvente de la peticion",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/UniqueClientIdCamping"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "operacion exitosa",
            "headers" : {
              "transactionId" : {
                "type" : "string",
                "description" : "identificador de la transacción en capa de servicios"
              }
            },
            "schema" : {
              "$ref" : "#/definitions/responseTracing"
            }
          },
          "404" : {
            "description" : "Error general",
            "headers" : {
              "transactionId" : {
                "type" : "string",
                "description" : "identificador de la transacción en capa de servicios"
              }
            },
            "schema" : {
              "$ref" : "#/definitions/Error"
            }
          }
        }
      }
    },
    "/portfolio/client/updatetracingclient" : {
      "post" : {
        "tags" : [ "marketing" ],
        "summary" : "Inserta el seguimiento que se le dio al cliente  y campana especifica",
        "description" : "Response la insercion del seguimiento fue correcta fue correcta!",
        "operationId" : "putTracingClient",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "ClientIdCamping",
          "description" : "Objeto envolvente de la peticion",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/UniqueTracingPut"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "operacion exitosa",
            "headers" : {
              "transactionId" : {
                "type" : "string",
                "description" : "identificador de la transacción en capa de servicios"
              }
            },
            "schema" : {
              "$ref" : "#/definitions/responseTracing"
            }
          },
          "404" : {
            "description" : "Error general",
            "headers" : {
              "transactionId" : {
                "type" : "string",
                "description" : "identificador de la transacción en capa de servicios"
              }
            },
            "schema" : {
              "$ref" : "#/definitions/Error"
            }
          }
        }
      }
    },
    "/portfolio/client/nextbestoffer" : {
      "post" : {
        "tags" : [ "marketing" ],
        "summary" : "Mejor producto a ofertar al cliente",
        "description" : "Response del mejor producto a ofertar",
        "operationId" : "getNextBestOfferByClient",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "uniqueClient",
          "description" : "Objeto envolvente de la peticion",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/UniqueClient"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "operacion exitosa",
            "headers" : {
              "transactionId" : {
                "type" : "string",
                "description" : "identificador de la transacción en capa de servicios"
              }
            },
            "schema" : {
              "$ref" : "#/definitions/responseNextBestOffer"
            }
          },
          "404" : {
            "description" : "Error general",
            "headers" : {
              "transactionId" : {
                "type" : "string",
                "description" : "identificador de la transacción en capa de servicios"
              }
            },
            "schema" : {
              "$ref" : "#/definitions/Error"
            }
          }
        }
      }
    },
    "/portfolio/client/detailsclients" : {
      "post" : {
        "tags" : [ "marketing" ],
        "summary" : "Detalle de cliente",
        "description" : "Responde  la Fecha de cliente (yyyy-MM-dd), anio de ingreso (yyyy) y calificacion del cliente (entero) cliente",
        "operationId" : "getDetailsClient",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "uniqueClient",
          "description" : "Objeto envolvente de la peticion",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/UniqueClient"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "operacion exitosa",
            "headers" : {
              "transactionId" : {
                "type" : "string",
                "description" : "identificador de la transacción en capa de servicios"
              }
            },
            "schema" : {
              "$ref" : "#/definitions/responseDetailsClient"
            }
          },
          "404" : {
            "description" : "Error general",
            "headers" : {
              "transactionId" : {
                "type" : "string",
                "description" : "identificador de la transacción en capa de servicios"
              }
            },
            "schema" : {
              "$ref" : "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions" : {
    "Root" : {
      "type" : "object",
      "properties" : {
        "requestRoot" : {
          "$ref" : "#/definitions/RequestRoot"
        },
        "responseRoot" : {
          "$ref" : "#/definitions/ResponseRoot"
        }
      },
      "description" : "xml"
    },
    "RequestRoot" : {
      "type" : "object",
      "properties" : {
        "idService" : {
          "type" : "string",
          "description" : "Identificador de servicio"
        },
        "id" : {
          "$ref" : "#/definitions/Parameter"
        },
        "campaingBranch" : {
          "$ref" : "#/definitions/CampaingBranch"
        },
        "uniqueClient" : {
          "$ref" : "#/definitions/UniqueClient"
        },
        "uniqueClients" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/UniqueClient"
          }
        },
        "uniqueClientIdCamping" : {
          "$ref" : "#/definitions/UniqueClientIdCamping"
        },
        "UniqueTracingPut" : {
          "$ref" : "#/definitions/UniqueTracingPut"
        }
      },
      "description" : "xml"
    },
    "ResponseRoot" : {
      "type" : "object",
      "properties" : {
        "idService" : {
          "type" : "string",
          "description" : "Identificador de servicio"
        },
        "campaigns" : {
          "type" : "array",
          "description" : "Listado de campañas activas",
          "items" : {
            "$ref" : "#/definitions/Campaigns"
          }
        },
        "detailsCamping" : {
          "$ref" : "#/definitions/DetailsCamping"
        },
        "traicing" : {
          "type" : "array",
          "description" : "Listado de seguimientos de un cliente para una campaña activa",
          "items" : {
            "$ref" : "#/definitions/Tracing"
          }
        },
        "clients" : {
          "type" : "array",
          "description" : "Listado de Clientes de una campana",
          "items" : {
            "$ref" : "#/definitions/UniqueClient"
          }
        },
        "detailsClient" : {
          "$ref" : "#/definitions/DetailsClient"
        },
        "nextBestOffer" : {
          "$ref" : "#/definitions/NextBestOffer"
        },
        "ClientCampaings" : {
          "type" : "array",
          "description" : "Listado de Clientes con campañas",
          "items" : {
            "$ref" : "#/definitions/UniqueClientCampaings"
          }
        },
        "issues" : {
          "$ref" : "#/definitions/Issues"
        }
      },
      "description" : "xml"
    },
    "responseCampaigns" : {
      "type" : "object",
      "properties" : {
        "campaigns" : {
          "type" : "array",
          "description" : "Listado de campañas activas",
          "items" : {
            "$ref" : "#/definitions/Campaigns"
          }
        },
        "issues" : {
          "$ref" : "#/definitions/Issues"
        }
      },
      "description" : "Respuesta del servicio Campaings",
      "example" : {
        "campaigns" : [ {
          "campaignDescriptionShort" : "campaignDescriptionShort",
          "campaignId" : "campaignId",
          "campaignDescription" : "campaignDescription"
        }, {
          "campaignDescriptionShort" : "campaignDescriptionShort",
          "campaignId" : "campaignId",
          "campaignDescription" : "campaignDescription"
        } ],
        "issues" : {
          "issue" : true,
          "detailsIssues" : [ {
            "error_code" : "error_code",
            "message" : "message"
          }, {
            "error_code" : "error_code",
            "message" : "message"
          } ]
        }
      }
    },
    "responseClientesCampaings" : {
      "type" : "object",
      "properties" : {
        "ClientCampaings" : {
          "type" : "array",
          "description" : "Listado de clientes con campañas activas",
          "items" : {
            "$ref" : "#/definitions/UniqueClientCampaings"
          }
        },
        "issues" : {
          "$ref" : "#/definitions/Issues"
        }
      },
      "description" : "Respuesta del servicio Campaings por cliente",
      "example" : {
        "ClientCampaings" : [ {
          "uniqueClientCountry" : "uniqueClientCountry",
          "camping" : [ {
            "campaignDescriptionShort" : "campaignDescriptionShort",
            "campaignId" : "campaignId",
            "campaignDescription" : "campaignDescription"
          }, {
            "campaignDescriptionShort" : "campaignDescriptionShort",
            "campaignId" : "campaignId",
            "campaignDescription" : "campaignDescription"
          } ],
          "uniqueClientFolio" : "uniqueClientFolio",
          "uniqueClientBranch" : "uniqueClientBranch",
          "uniqueClientChannel" : "uniqueClientChannel"
        }, {
          "uniqueClientCountry" : "uniqueClientCountry",
          "camping" : [ {
            "campaignDescriptionShort" : "campaignDescriptionShort",
            "campaignId" : "campaignId",
            "campaignDescription" : "campaignDescription"
          }, {
            "campaignDescriptionShort" : "campaignDescriptionShort",
            "campaignId" : "campaignId",
            "campaignDescription" : "campaignDescription"
          } ],
          "uniqueClientFolio" : "uniqueClientFolio",
          "uniqueClientBranch" : "uniqueClientBranch",
          "uniqueClientChannel" : "uniqueClientChannel"
        } ],
        "issues" : {
          "issue" : true,
          "detailsIssues" : [ {
            "error_code" : "error_code",
            "message" : "message"
          }, {
            "error_code" : "error_code",
            "message" : "message"
          } ]
        }
      }
    },
    "Campaigns" : {
      "type" : "object",
      "properties" : {
        "campaignId" : {
          "type" : "string",
          "description" : "Id de campaña"
        },
        "campaignDescriptionShort" : {
          "type" : "string",
          "description" : "Descripcion de campaña Corta"
        },
        "campaignDescription" : {
          "type" : "string",
          "description" : "Descripcion de campaña Extendida"
        }
      },
      "description" : "Listado de campañas activas",
      "example" : {
        "campaignDescriptionShort" : "campaignDescriptionShort",
        "campaignId" : "campaignId",
        "campaignDescription" : "campaignDescription"
      }
    },
    "responseTracing" : {
      "type" : "object",
      "properties" : {
        "tracings" : {
          "type" : "array",
          "description" : "Listado de Seguimintos del Cliente",
          "items" : {
            "$ref" : "#/definitions/Tracing"
          }
        },
        "issues" : {
          "$ref" : "#/definitions/Issues"
        }
      },
      "description" : "Respuesta del servicio Campaings",
      "example" : {
        "tracings" : [ {
          "tracingDescription" : "tracingDescription",
          "tracingId" : "tracingId",
          "campaignId" : "campaignId",
          "campaignDescription" : "campaignDescription"
        }, {
          "tracingDescription" : "tracingDescription",
          "tracingId" : "tracingId",
          "campaignId" : "campaignId",
          "campaignDescription" : "campaignDescription"
        } ],
        "issues" : {
          "issue" : true,
          "detailsIssues" : [ {
            "error_code" : "error_code",
            "message" : "message"
          }, {
            "error_code" : "error_code",
            "message" : "message"
          } ]
        }
      }
    },
    "Tracing" : {
      "type" : "object",
      "properties" : {
        "campaignId" : {
          "type" : "string",
          "description" : "Id de campaña"
        },
        "campaignDescription" : {
          "type" : "string",
          "description" : "Descripcion de campaña"
        },
        "tracingId" : {
          "type" : "string",
          "description" : "Id de Seguimieto"
        },
        "tracingDescription" : {
          "type" : "string",
          "description" : "Descripcion de seguimiento"
        }
      },
      "description" : "Seguimiento de cliente",
      "example" : {
        "tracingDescription" : "tracingDescription",
        "tracingId" : "tracingId",
        "campaignId" : "campaignId",
        "campaignDescription" : "campaignDescription"
      }
    },
    "responseClients" : {
      "type" : "object",
      "properties" : {
        "camping" : {
          "$ref" : "#/definitions/Campaigns"
        },
        "clients" : {
          "type" : "array",
          "description" : "Listado de Clientes de una campana",
          "items" : {
            "$ref" : "#/definitions/UniqueClient"
          }
        },
        "issues" : {
          "$ref" : "#/definitions/Issues"
        }
      },
      "description" : "Respuesta del servicio Clients",
      "example" : {
        "camping" : {
          "campaignDescriptionShort" : "campaignDescriptionShort",
          "campaignId" : "campaignId",
          "campaignDescription" : "campaignDescription"
        },
        "clients" : [ {
          "uniqueClientCountry" : "uniqueClientCountry",
          "uniqueClientFolio" : "uniqueClientFolio",
          "uniqueClientBranch" : "uniqueClientBranch",
          "uniqueClientChannel" : "uniqueClientChannel"
        }, {
          "uniqueClientCountry" : "uniqueClientCountry",
          "uniqueClientFolio" : "uniqueClientFolio",
          "uniqueClientBranch" : "uniqueClientBranch",
          "uniqueClientChannel" : "uniqueClientChannel"
        } ],
        "issues" : {
          "issue" : true,
          "detailsIssues" : [ {
            "error_code" : "error_code",
            "message" : "message"
          }, {
            "error_code" : "error_code",
            "message" : "message"
          } ]
        }
      }
    },
    "responseDetailsClient" : {
      "type" : "object",
      "properties" : {
        "detailsClient" : {
          "$ref" : "#/definitions/DetailsClient"
        },
        "issues" : {
          "$ref" : "#/definitions/Issues"
        }
      },
      "description" : "Respuesta del servicio DetailsClient",
      "example" : {
        "detailsClient" : {
          "birthday" : "birthday",
          "yearback" : "yearback",
          "ranking" : "ranking"
        },
        "issues" : {
          "issue" : true,
          "detailsIssues" : [ {
            "error_code" : "error_code",
            "message" : "message"
          }, {
            "error_code" : "error_code",
            "message" : "message"
          } ]
        }
      }
    },
    "DetailsClient" : {
      "type" : "object",
      "properties" : {
        "birthday" : {
          "type" : "string",
          "description" : "cumpleanios de cliente"
        },
        "yearback" : {
          "type" : "string",
          "description" : "anio de ingreso como cliente"
        },
        "ranking" : {
          "type" : "string",
          "description" : "calificacion otorgada"
        }
      },
      "description" : "Listado de productos",
      "example" : {
        "birthday" : "birthday",
        "yearback" : "yearback",
        "ranking" : "ranking"
      }
    },
    "responseNextBestOffer" : {
      "type" : "object",
      "properties" : {
        "nextBestOffer" : {
          "$ref" : "#/definitions/NextBestOffer"
        },
        "issues" : {
          "$ref" : "#/definitions/Issues"
        }
      },
      "description" : "Respuesta del servicio NextBestOffer",
      "example" : {
        "nextBestOffer" : {
          "productLine" : "productLine",
          "description" : "description",
          "SKU" : "SKU"
        },
        "issues" : {
          "issue" : true,
          "detailsIssues" : [ {
            "error_code" : "error_code",
            "message" : "message"
          }, {
            "error_code" : "error_code",
            "message" : "message"
          } ]
        }
      }
    },
    "NextBestOffer" : {
      "type" : "object",
      "properties" : {
        "SKU" : {
          "type" : "string",
          "description" : "SKU del producto"
        },
        "description" : {
          "type" : "string",
          "description" : "Descripcion del producto"
        },
        "productLine" : {
          "type" : "string",
          "description" : "Linea del producto"
        }
      },
      "description" : "Producto a ofertar al cliente",
      "example" : {
        "productLine" : "productLine",
        "description" : "description",
        "SKU" : "SKU"
      }
    },
    "responseDetailsCamping" : {
      "type" : "object",
      "properties" : {
        "detailsCamping" : {
          "$ref" : "#/definitions/DetailsCamping"
        },
        "issues" : {
          "$ref" : "#/definitions/Issues"
        }
      },
      "description" : "Respuesta del servicio DetailsClient",
      "example" : {
        "detailsCamping" : {
          "descriptionCamping" : "descriptionCamping",
          "dateExpiry" : "dateExpiry",
          "validity" : "validity",
          "campaingId" : "campaingId",
          "typeCamping" : "typeCamping"
        },
        "issues" : {
          "issue" : true,
          "detailsIssues" : [ {
            "error_code" : "error_code",
            "message" : "message"
          }, {
            "error_code" : "error_code",
            "message" : "message"
          } ]
        }
      }
    },
    "DetailsCamping" : {
      "type" : "object",
      "properties" : {
        "campaingId" : {
          "type" : "string",
          "description" : "Identificador de campana"
        },
        "typeCamping" : {
          "type" : "string",
          "description" : "tipo de campana"
        },
        "descriptionCamping" : {
          "type" : "string",
          "description" : "Descripcion extendida  de la campana"
        },
        "validity" : {
          "type" : "string",
          "description" : "Indica si la campana puede expirar"
        },
        "dateExpiry" : {
          "type" : "string",
          "description" : "Fecha de expiracion de la campana"
        }
      },
      "description" : "Detalle de Campanas",
      "example" : {
        "descriptionCamping" : "descriptionCamping",
        "dateExpiry" : "dateExpiry",
        "validity" : "validity",
        "campaingId" : "campaingId",
        "typeCamping" : "typeCamping"
      }
    },
    "CampaingBranch" : {
      "type" : "object",
      "required" : [ "branch", "campaingId" ],
      "properties" : {
        "campaingId" : {
          "type" : "string",
          "description" : "Identificador de campana"
        },
        "branch" : {
          "type" : "string",
          "description" : "Sucursal"
        }
      },
      "description" : "Objeto para peticion de clienes  id de campana y sucursal",
      "example" : {
        "campaingId" : "campaingId",
        "branch" : "branch"
      }
    },
    "UniqueClient" : {
      "type" : "object",
      "required" : [ "uniqueClientBranch", "uniqueClientChannel", "uniqueClientCountry", "uniqueClientFolio" ],
      "properties" : {
        "uniqueClientCountry" : {
          "type" : "string",
          "description" : "Pais de cliente unico"
        },
        "uniqueClientChannel" : {
          "type" : "string",
          "description" : "Canal de cliente unico"
        },
        "uniqueClientBranch" : {
          "type" : "string",
          "description" : "Sucursal de cliente unico"
        },
        "uniqueClientFolio" : {
          "type" : "string",
          "description" : "Folio de cliente unico"
        }
      },
      "description" : "Objeto con informacion de cliente unico",
      "example" : {
        "uniqueClientCountry" : "uniqueClientCountry",
        "uniqueClientFolio" : "uniqueClientFolio",
        "uniqueClientBranch" : "uniqueClientBranch",
        "uniqueClientChannel" : "uniqueClientChannel"
      }
    },
    "UniqueClientCampaings" : {
      "type" : "object",
      "required" : [ "uniqueClientBranch", "uniqueClientChannel", "uniqueClientCountry", "uniqueClientFolio" ],
      "properties" : {
        "uniqueClientCountry" : {
          "type" : "string",
          "description" : "Pais de cliente unico"
        },
        "uniqueClientChannel" : {
          "type" : "string",
          "description" : "Canal de cliente unico"
        },
        "uniqueClientBranch" : {
          "type" : "string",
          "description" : "Sucursal de cliente unico"
        },
        "uniqueClientFolio" : {
          "type" : "string",
          "description" : "Folio de cliente unico"
        },
        "camping" : {
          "type" : "array",
          "description" : "Listado de Campanas del cliente",
          "items" : {
            "$ref" : "#/definitions/Campaigns"
          }
        }
      },
      "description" : "Objeto con informacion de cliente unico",
      "example" : {
        "uniqueClientCountry" : "uniqueClientCountry",
        "camping" : [ {
          "campaignDescriptionShort" : "campaignDescriptionShort",
          "campaignId" : "campaignId",
          "campaignDescription" : "campaignDescription"
        }, {
          "campaignDescriptionShort" : "campaignDescriptionShort",
          "campaignId" : "campaignId",
          "campaignDescription" : "campaignDescription"
        } ],
        "uniqueClientFolio" : "uniqueClientFolio",
        "uniqueClientBranch" : "uniqueClientBranch",
        "uniqueClientChannel" : "uniqueClientChannel"
      }
    },
    "UniqueClients" : {
      "type" : "array",
      "description" : "Lista de clientes unicos",
      "items" : {
        "$ref" : "#/definitions/UniqueClient"
      }
    },
    "UniqueClientIdCamping" : {
      "type" : "object",
      "required" : [ "uniqueCampingId", "uniqueClientBranch", "uniqueClientChannel", "uniqueClientCountry", "uniqueClientFolio" ],
      "properties" : {
        "uniqueCampingId" : {
          "type" : "string",
          "description" : "Id de campana"
        },
        "uniqueClientCountry" : {
          "type" : "string",
          "description" : "Pais de cliente unico"
        },
        "uniqueClientChannel" : {
          "type" : "string",
          "description" : "Canal de cliente unico"
        },
        "uniqueClientBranch" : {
          "type" : "string",
          "description" : "Sucursal de cliente unico"
        },
        "uniqueClientFolio" : {
          "type" : "string",
          "description" : "Folio de cliente unico"
        }
      },
      "description" : "Objeto con informacion de cliente unico",
      "example" : {
        "uniqueClientCountry" : "uniqueClientCountry",
        "uniqueClientFolio" : "uniqueClientFolio",
        "uniqueClientBranch" : "uniqueClientBranch",
        "uniqueClientChannel" : "uniqueClientChannel",
        "uniqueCampingId" : "uniqueCampingId"
      }
    },
    "UniqueTracingPut" : {
      "type" : "object",
      "required" : [ "uniqueCampingId", "uniqueClientBranch", "uniqueClientChannel", "uniqueClientCountry", "uniqueClientFolio", "uniqueTracing" ],
      "properties" : {
        "uniqueCampingId" : {
          "type" : "string",
          "description" : "id Campana"
        },
        "uniqueTracing" : {
          "type" : "string",
          "description" : "Seguimiento registrado"
        },
        "uniqueClientCountry" : {
          "type" : "string",
          "description" : "Pais de cliente unico"
        },
        "uniqueClientChannel" : {
          "type" : "string",
          "description" : "Canal de cliente unico"
        },
        "uniqueClientBranch" : {
          "type" : "string",
          "description" : "Sucursal de cliente unico"
        },
        "uniqueClientFolio" : {
          "type" : "string",
          "description" : "Folio de cliente unico"
        }
      },
      "description" : "Objeto con informacion de cliente unico y seguimiento para insertar seguiento de una campana",
      "example" : {
        "uniqueClientCountry" : "uniqueClientCountry",
        "uniqueClientFolio" : "uniqueClientFolio",
        "uniqueTracing" : "uniqueTracing",
        "uniqueClientBranch" : "uniqueClientBranch",
        "uniqueClientChannel" : "uniqueClientChannel",
        "uniqueCampingId" : "uniqueCampingId"
      }
    },
    "Error" : {
      "type" : "object",
      "properties" : {
        "detailsError" : {
          "type" : "array",
          "description" : "Detalle de error",
          "items" : {
            "$ref" : "#/definitions/ErrorType"
          }
        }
      },
      "description" : "Arreglo de errores generales"
    },
    "ErrorType" : {
      "type" : "object",
      "properties" : {
        "error_code" : {
          "type" : "string",
          "description" : "Codigo de error"
        },
        "message" : {
          "type" : "string",
          "description" : "Mensaje de error"
        },
        "transactionID" : {
          "type" : "string",
          "description" : "Identificador de transacion"
        }
      }
    },
    "Issues" : {
      "type" : "object",
      "required" : [ "issue" ],
      "properties" : {
        "issue" : {
          "type" : "boolean",
          "description" : "Existen problemas"
        },
        "detailsIssues" : {
          "type" : "array",
          "description" : "Detalle de error",
          "items" : {
            "$ref" : "#/definitions/IssuesType"
          }
        }
      },
      "description" : "Problemas durante la transacion",
      "example" : {
        "issue" : true,
        "detailsIssues" : [ {
          "error_code" : "error_code",
          "message" : "message"
        }, {
          "error_code" : "error_code",
          "message" : "message"
        } ]
      }
    },
    "IssuesType" : {
      "type" : "object",
      "properties" : {
        "error_code" : {
          "type" : "string",
          "description" : "Codigo de problema"
        },
        "message" : {
          "type" : "string",
          "description" : "Mensaje de problema"
        }
      },
      "example" : {
        "error_code" : "error_code",
        "message" : "message"
      }
    },
    "Parameter" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string"
        }
      },
      "description" : "Numero de sucursal o idCliente"
    }
  }
}